### PR TITLE
audio: Make sure about to finish skips unplayable tracks

### PR DESCRIPTION
**Pull request by adamcik**

### CODE REVIEW

**Comment by jodal** [comment]
LGTM. Can you add a test?

**Comment by adamcik** [comment]
Probably, but not tonight :-)

**Comment by jodal** [comment]
I'm suspecting that you can steal something from `test_next_skips_over_unplayable_track()` in #1444.

**Comment by adamcik** [comment]
To some degree, but I need to trigger the error at a different place. And we also ignore any errors that get the URI set but then fail in GStreamer. There is #1441 for that.

**Comment by adamcik** [comment]
Expanded the tests to also check for when `change_track` raises exceptions or returns `False`. Currently this is done at `translate_uri` level, but it could just as well be directly in `change_track`. Anyway, this is now tested for next/prev/eot cases.

**Pull request merged**
