### PR TITLE
Py3 MPD frontend - part one

### PR DESCRIPTION
**Pull request by kingosticks**
Requires #1815 

`LineProtocol`'s `delimiter` and `terminator` are defined as unicode strings. `delimiter` is only ever used for parsing request bytes. `terminator` is used both for raw requests (bytes) and our responses (unicode). 

tests/mpd/test_status.py possibly requires a change to Pykka.

### CODE REVIEW

**Comment by kingosticks** [comment]
Simply prefixing with `b` was my first attempt but it unravelled in `MpdSession.on_line_received` where `response` is unicode. This seemed less changes but conceptually it seems wrong since `LineProtocol` stuff should probably be bytes....

**Comment by kingosticks** [comment]
> Should we unignore the internal/network tests too?

They are currently failing.

**Comment by jodal** [comment]
OK. Other than this being marked as draft, I think it's ready to merge. Maybe rebase to get rid of the first two commits which already exists in develop.

**Comment by kingosticks** [comment]
After my earlier comment I'm re-working it to have `delimiter` and `terminator` as bytes. I think that makes more sense. And to fix those network tests.

**Comment by kingosticks** [comment]
I got tests/internal/network/test_lineprotocol.py going but the other network tests still need work.

**Comment by kingosticks** [comment]
The tox cache busting doesn't seem to have worked.

**Comment by jodal** [comment]
CircleCI's cache busting should work properly with the change I just did on develop in 637aba2d1dffb730f46eba1dfbe0d5d84cc31aab.

**Comment by kingosticks** [comment]
I forgot I need to rebase to actually pick that change up! Wish there was a button for that in GitHub's interface here.

**Comment by kingosticks** [comment]
Fixed now. 

FYI, I left test_lineprotocol.py terminator/delimiter/recv_buffer stuff mostly working with unicode when really they should all be only using bytes so that we test how we actually use it. I could fix that. Maybe I should fix that....

**Comment by kingosticks** [comment]
Fixed the other network tests and made sure things that use bytes are tested with bytes.

**Comment by jodal** [comment]
Rebase needed.

**Comment by jodal** [comment]
I rebased and merged this in commit 30f76d53cd7c615bcfd8be108c708673cfd5e595.

**Pull request closed without merging**
