### PR TITLE
Propagate stream metadata

### PR DESCRIPTION
**Pull request by AlexandrePTJ**
This is a proposal for #270

### CODE REVIEW

**Comment by AlexandrePTJ** [comment]
Last commit introduce a bug : if going from a stream to a local media, currentsong might return the stream metadata instead.

**Comment by AlexandrePTJ** [comment]
That's ok, no problem with local media

**Comment by jodal** [comment]
@adamcik There are new commits to review in this PR :-)

**Comment by adamcik** [comment]
Now I just have to merge/rebase this cleanly against my gapless branch which has some similar changes  :p 

Thanks for taking the time implement this long missing piece.

**Comment by AlexandrePTJ** [comment]
Thanks, you're welcome :)

**Pull request merged**
