### PR TITLE
Skip over unplayable tracks when paused

### PR DESCRIPTION
**Pull request by jcass77**
Proposed fixes for https://github.com/mopidy/mopidy/issues/1378.

This PR is based on https://github.com/mopidy/mopidy/pull/1356 as the changes overlap somewhat, so should probably be merged in that sequence.

The quick fix in ```PlaybackController._change_track``` is becoming little messy as it now includes hacks for three issues :( But a lot of this has changed in gapless so should be ok if there are no further changes?

### CODE REVIEW

**Comment by jodal** [comment]
PR #1356 has been merged into release-1.1. Can you rebase and force-push this PR?

**Comment by jcass77** [comment]
Yes certainly. I'm away from keyboard for a few days but should be able to pick this up again on Saturday.

**Comment by jodal** [comment]
Great! Just in time for a Mopidy 1.1.2 release this weekend :-)

**Comment by jcass77** [comment]
I've performed the rebase and force-pushed to release-1.1.

Thank you!

**Comment by jodal** [comment]
Thanks :-)

**Pull request merged**
