### PR TITLE
Increase logging level for invalid config

### LINKED ISSUE #1878: Warn on unrecognised config section
I've recently (apparently without realising) been updated to Mopidy 3.0, which, as I now know, doesn't include the MPD frontend in the core anymore and apparently didn't pull it in as a dependency, so I was left trying to troubleshoot why my Mopidy server was suddenly not listening on port 6600 anymore.
A feature that would've been very helpful would be a warning of some kind if there is a section in the configuration that has no corresponding extension - for example: "configuration for missing extension mpd - do you need to install mopidy-mpd?" (with the latter part left out for any configuration section that doesn't match the well-known first-party extensions, or rewritten in a more generic way).
As of now, the only sign you get the mpd extensions is gone is that it disappears from the listed extensions and enabled frontends, and I feel like a warning like that would be very helpful for future troubleshooting.

### PR DESCRIPTION
**Pull request by jjok**
Closes #1878 

I added an `unknownsection` to my config and an `unknownvalue` to `scrobbler` to see how it looks. Turns out I already config set for 2 extensions that I don't have installed.
```
INFO     2020-03-17 23:08:11,518 [1:MainThread] mopidy.config
  Loading config from command line options
WARNING  2020-03-17 23:08:11,522 [1:MainThread] mopidy.config
  Ignoring config section 'local': A matching extension was not found
WARNING  2020-03-17 23:08:11,522 [1:MainThread] mopidy.config
  Ignoring config section 'soundcloud': A matching extension was not found
WARNING  2020-03-17 23:08:11,522 [1:MainThread] mopidy.config
  Ignoring config section 'unknownsection': A matching extension was not found
INFO     2020-03-17 23:08:12,261 [1:MainThread] mopidy.__main__
  Enabled extensions: gmusic, podcast, softwaremixer, mpd, http
INFO     2020-03-17 23:08:12,261 [1:MainThread] mopidy.__main__
  Disabled extensions: iris, spotify, stream, m3u, file, scrobbler
WARNING  2020-03-17 23:08:12,262 [1:MainThread] mopidy.__main__
  Found scrobbler configuration errors. The extension has been automatically disabled:
WARNING  2020-03-17 23:08:12,262 [1:MainThread] mopidy.__main__
    scrobbler/unknownvalue unknown config key.
WARNING  2020-03-17 23:08:12,262 [1:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.
```

### CODE REVIEW

**Comment by kingosticks** [comment]
To be honest I don't think the message needed to change as the punctuation is odd now. But doesn't really matter.

**Comment by jodal** [comment]
The text comes directly from my comment in the issue. Better if we replace `: A` with `because a`?

**Comment by kingosticks** [comment]
Ahh. Yes.

But wouldn't you also get this warning if you had a typo in a non-extension section name e.g. `core`.

**Comment by jjok** [comment]
> But wouldn't you also get this warning if you had a typo in a non-extension section name e.g. core.

Ahh. That's not something that I tried. I'll give it a go.

**Comment by jjok** [comment]
> Ahh. Yes.
> 
> But wouldn't you also get this warning if you had a typo in a non-extension section name e.g. `core`.

You get a fatal error if you have a typo in the main configuration.

```
[core]
unknown = value
```

```
WARNING  2020-03-18 18:35:13,989 [1:MainThread] mopidy.__main__
  Found fatal core configuration errors:
WARNING  2020-03-18 18:35:13,989 [1:MainThread] mopidy.__main__
    core/unknown unknown config key.
ERROR    2020-03-18 18:35:13,989 [1:MainThread] mopidy.__main__
  Please fix fatal configuration errors, exiting...
```

**Comment by kingosticks** [comment]
Excellent!

**Pull request merged**
