### PR TITLE
Re-set volume explicitly to the current level whenever changing tracks.

### PR DESCRIPTION
**Pull request by jcass77**
Workaround for issue #886.

### CODE REVIEW

**Comment by adamcik** [comment]
Note that https://github.com/adamcik/mopidy/tree/feature/implement-gapless might break this and/or make it unneeded.

Also for a workaround like this a comment referring to the issue number is nice so we can keep track on why it was added.

**Comment by jodal** [comment]
+1 to this simple workaround

@adamcik Do you have any ideas on how to fix this properly and permanently?

**Comment by jodal** [comment]
@jcass77 I didn't notice that you had pushed a fix to @adamcik's comment until I went checking the PR now. Please comment when you update the PR, as GitHub doesn't send mail notifications on new commits in a PR. :-)

**Comment by adamcik** [comment]
Hmm, we should probably get this in so we at least have a workaround for the next release. Then for the following release I hope we can remove this again depending on how the gapless changes effect this issue.

@jcass77 could we ping you when we have that code ready enough for you to give it a quick spin?

**Comment by jcass77** [comment]
@adamcik yes please.

**Comment by adamcik** [comment]
Note that this was opened against master, we normally only merge things against develop before cutting a release to master. Whoops...

**Comment by jodal** [comment]
I manually merged this into develop.

**Comment by jcass77** [comment]
Works for me - thank you.

**Comment by ZenithDK** [comment]
Should this get a changelog entry?

**Comment by jodal** [comment]
If it doesn't already, yes!

**Comment by jodal** [comment]
```
- Add workaround for volume not persisting across tracks on OS X.
  (Issue: :issue:`886`, PR: :issue:`958`)                        
```

**Comment by ZenithDK** [comment]
I don't have access to my local dev branches right now, so tagging this so we don't miss it.

**Pull request merged**
