### PR TITLE
config: Add config for data/config/cache directories

### PR DESCRIPTION
**Pull request by dprokic**
Issue #843

I will add more commits during the day. Next thing I will work on are the tests.

### CODE REVIEW

**Comment by jodal** [comment]
Small nitpick: I'd reorder the core config values, so `max_tracklist_length` comes last.

**Comment by dprokic** [comment]
OK.

**Comment by adamcik** [comment]
:+1:

**Comment by jodal** [comment]
Thanks!

**Comment by dprokic** [comment]
Pleasure is mine :-)
26.07.2015. 12.26, "Stein Magnus Jodal" <notifications@github.com> је
написао/ла:

**Pull request merged**
