### PR TITLE
Fix/1133 Add nextsong and nextsongid to mpd status command

### LINKED ISSUE #1516: Missing nextsong id
MPD provides a nextsong id in the answer to the status command, mopidy seems not to provide this information, yet.

### PR DESCRIPTION
**Pull request by ismailof**
The PR adds nextsong and nextsongid to mpd status command.
The ID of the next track to be played is provided by `tracklist.get_next_tlid()`

It also fixes #1516 (duplicated)

### CODE REVIEW

**Comment by adamcik** [comment]
https://www.musicpd.org/doc/protocol/command_reference.html#status_commands for my own reference.

**Comment by adamcik** [comment]
A quick changelog entry for this would be awesome, rest looks good to me.

**Comment by ismailof** [comment]
I'm not at home for a while. When I come back next week I'll add the note in the changelog.

**Comment by adamcik** [comment]
Perfect, thanks for the contribution and following up on this.

I looked into the now failing travis test, looks unrelated to your change so just double checking that before merging :-)

**Comment by adamcik** [comment]
I rebuilt https://travis-ci.org/mopidy/mopidy/builds/137349654 which was known good and it now fails... So going ahead and merging your change and we'll have to unbreak the build for everyone using a newer flake8.

**Pull request merged**
